version: '2'

services: 
  tass-reader-run: 
    container_name: tass-reader-run
    build: .
    command: go run main.go
    volumes: 
      - ./:/go/src/app
    working_dir: /go/src/app
    ports: 
      - "3030:3001"
    environment: 
      PORT: 3001